spring:
  quartz:
    scheduler-name: lanvander-SpringBoot-Job
    overwrite-existing-jobs: true
    job-store-type: jdbc
    wait-for-jobs-to-complete-on-shutdown: true
    jdbc:
      comment-prefix: '#'
      initialize-schema: never
    restart-on-deploy: 0 #1 - 重启, other - 不重启

  datasource:
    url: jdbc:mysql://localhost:3306/lanvanderframework?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: lanvander
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: lanvander.quartz.springboot.request
